# docker exec -it <container-name> /bin/sh
services:
  # go-shop-console:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - mongodb
  #   environment:
  #     - MONGO_URI=mongodb://root:P@ssw0rd!23@mongodb:27017/shopGo
  #   tty: true # Enables interactive mode for console apps

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGO_URI}

volumes:
  mongo_data:
